BEGIN;

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    source_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS books (
    upc TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    product_url TEXT NOT NULL UNIQUE,
    category_id INTEGER NOT NULL REFERENCES categories(id),
    image_url TEXT,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    price_list NUMERIC(10, 2) NOT NULL CHECK (price_list >= 0),
    price_excl_tax NUMERIC(10, 2) NOT NULL CHECK (price_excl_tax >= 0),
    price_incl_tax NUMERIC(10, 2) NOT NULL CHECK (price_incl_tax >= 0),
    tax NUMERIC(10, 2) NOT NULL CHECK (tax >= 0),
    stock_quantity INTEGER NOT NULL CHECK (stock_quantity >= 0),
    availability_text TEXT,
    review_count INTEGER NOT NULL DEFAULT 0 CHECK (review_count >= 0),
    description TEXT,
    scraped_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_books_category_id ON books(category_id);
CREATE INDEX IF NOT EXISTS idx_books_stock_quantity ON books(stock_quantity);
CREATE INDEX IF NOT EXISTS idx_books_rating ON books(rating);
CREATE INDEX IF NOT EXISTS idx_books_review_count ON books(review_count);

CREATE OR REPLACE VIEW books_catalog AS
SELECT
    b.upc,
    b.title,
    c.name AS category,
    b.product_url,
    b.image_url,
    b.rating,
    b.price_list,
    b.price_excl_tax,
    b.price_incl_tax,
    b.tax,
    b.stock_quantity,
    CASE
        WHEN b.stock_quantity = 0 THEN 'rupture'
        WHEN b.stock_quantity <= 5 THEN 'stock faible'
        ELSE 'stock disponible'
    END AS stock_status,
    b.review_count,
    b.description,
    b.scraped_at,
    b.updated_at
FROM books AS b
JOIN categories AS c ON c.id = b.category_id;

CREATE OR REPLACE VIEW books_stock_alerts AS
SELECT *
FROM books_catalog
WHERE stock_quantity <= 5;

CREATE OR REPLACE VIEW books_best_rated AS
SELECT *
FROM books_catalog
WHERE rating >= 4;

COMMENT ON TABLE categories IS 'Categories du catalogue Books to Scrape.';
COMMENT ON TABLE books IS 'Livres collectes depuis les pages liste et les fiches produit.';
COMMENT ON COLUMN books.upc IS 'Identifiant produit stable utilise comme cle primaire.';
COMMENT ON COLUMN books.price_list IS 'Prix affiche sur la page de liste.';
COMMENT ON COLUMN books.price_excl_tax IS 'Prix hors taxe indique sur la fiche produit.';
COMMENT ON COLUMN books.price_incl_tax IS 'Prix TTC indique sur la fiche produit.';
COMMENT ON COLUMN books.tax IS 'Montant de taxe indique sur la fiche produit.';
COMMENT ON COLUMN books.stock_quantity IS 'Stock reel extrait depuis la fiche produit.';
COMMENT ON COLUMN books.review_count IS 'Nombre d''avis extrait depuis la fiche produit.';
COMMENT ON VIEW books_stock_alerts IS 'Livres en rupture ou en stock faible.';
COMMENT ON VIEW books_best_rated IS 'Livres notes 4 ou 5 etoiles.';

COMMIT;
